noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

set clipboard+=unnamedplus
syntax on
set number
set visualbell
set encoding=utf-8
filetype plugin indent on

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set ruler

colorscheme monokai
